### ISSUE TITLE
BW v2 API?

### ISSUE THREAD

**Issue by alexthekid07** [Bandwidth/csharp-bandwidth-iris#50]
Are there any plans to update this to work with BW's newer "v2" APIs?

**Comment by ajrice6713** [comment]
Hey Alex,

There are plans - we are working to generate new SDK's for our IRIS API across all languages using an auto generation service that creates the SDK from our open API specification. 

We are in the final stages of development and working through some final bugs, but hope to have the release publicly available in Q1 of 2021.

**Comment by alexthekid07** [comment]
Thanks for the update! I currently use the REST endpoints but it'd be a lot cleaner to have a library. I look forward to trying it out.

**Comment by ajrice6713** [comment]
Alex, 

If you are interested, you can open a support ticket through our ticketing system and I might be able to get you early access. The ordering functionality is currently broken, but the rest of the SDK should be functional.

Let me know the ticket # if you are interested and I can get that taken care of, otherwise I will close out this issue for the time being!

**Comment by alexthekid07** [comment]
> Let me know the ticket # if you are interested and I can get that taken care of, otherwise I will close out this issue for the time being!

Thanks, I opened ticket #3761487 (from the name "Derek") under API/SDK issues.
