### ISSUE TITLE
[BUG] TnOptions.Get BandwidthIrisException on orders that contain errors

### ISSUE THREAD

**Issue by realmagic-eanes** [Bandwidth/csharp-bandwidth-iris#83]
### Checklist
 - [x] Have you provided a description of the bug?
 - [x] Have you provided your Environment information?
 - [x] Have you provided a sample code snippet?
 - [x] Have you provided a stack trace?
 - [x] Have you outlined the expected behavior?

### Description
Calling TnOptions.Get on an order that contains an error results in a BandwidthIrisException being thrown.

### Environment Information

 - OS Version: Windows 11
 - SDK Version: 7.0.0
 - Environment: NET Core 8.0

### Sample Code Snippet
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TnOptionOrder>
    <OrderCreateDate>2024-11-07T18:33:35.729Z</OrderCreateDate>
    <AccountId>xxxxxxx</AccountId>
    <CreatedByUser>xxxxxxx</CreatedByUser>
    <OrderId>98c712a4-7b7d-4a1f-9789-e4a5f73a29ac</OrderId>
    <LastModifiedDate>2024-11-07T18:34:08.457Z</LastModifiedDate>
    <ProcessingStatus>PARTIAL</ProcessingStatus>
    <TnOptionGroups>
        <TnOptionGroup>
            <Sms>on</Sms>
            <A2pSettings>
                <CampaignId>xxxxxx</CampaignId>
                <Action>asSpecified</Action>
            </A2pSettings>
            <TelephoneNumbers>
                <TelephoneNumber>xxxxxxx</TelephoneNumber>
            </TelephoneNumbers>
        </TnOptionGroup>
    </TnOptionGroups>
    <ErrorList>
        <Error>
            <Code>5229</Code>
            <Description>An error occurred while provisioning TN with Campaign 'xxxxxx': The TN could not be provisioned because per the downstream partner, the TN is not owned by the customer or the NNID is not authorized to be used. Please verify ownership of the TN or verify the NNID submitted in the request and try again. (error #1026).</Description>
            <TelephoneNumber>xxxxxxx</TelephoneNumber>
        </Error>
    </ErrorList>
    <Warnings>
        <Warning>
            <Description>SMS is already Enabled or number is in processing.</Description>
            <TelephoneNumber>xxxxxxx</TelephoneNumber>
        </Warning>
    </Warnings>
</TnOptionOrder>
```

### Stack Trace
```shell
Bandwidth.Iris.BandwidthIrisException: An error occurred while provisioning TN with Campaign 'xxxxxx': The TN could not be provisioned because per the downstream partner, the TN is not owned by the customer or the NNID is not authorized to be used. Please verify ownership of the TN or verify the NNID submitted in the request and try again. (error #1026).
   at Bandwidth.Iris.Client.MakeGetRequest(String path, IDictionary`2 query, String id, Boolean disposeResponse)
   at Bandwidth.Iris.Client.MakeGetRequest[TResult](String path, IDictionary`2 query, String id)
   at Bandwidth.Iris.Model.TnOptions.Get(Client client, String orderId)

```

### Expected Behavior
Since this is a get request and the order object was retrieved successfully, the expected behavior is that the order object would be returned without an exception.

**Comment by ajrice6713** [comment]
Hey @realmagic-eanes - Thanks for raising this up 

agreed it makes sense to not raise an exception here - I will take a look at this and get a fix in the works. 

Tell Will hello for me 😉

**Comment by ajrice6713** [comment]
@realmagic-eanes curious to get your thoughts on this issue 

for whatever reason, when this SDK was built (you can check the git blame, i had nothing to do with this @wlicamele) - every request, regardless of method, goes through this [`checkResponse`](https://github.com/Bandwidth/csharp-bandwidth-iris/blob/289c7d869c41527bcccb9a7d329feddbcaf3db2e/Bandwidth.Iris/Client.cs#L397) method, which essentially parses the XML body, looks for elements named `ErrorCode` and `Description` and - if found - throws an exception - before checking any status codes. 

I would be in favor of removing this logic altogether - I don't think it makes sense in any case to throw an exception on a 2xx status code or because an XML element in the response has `Error` in the name - but that would be a pretty large breaking change and I don't know what the blast radius would be there for other methods/API operations.

However, if you don't foresee any issues, I can get a PR up with that change and we can give it a shot.

**Comment by realmagic-eanes** [comment]
I understand avoiding the breaking change since this is an existing pattern.  Would it be possible to add an optional setting that I can pass to the get call which would check the status before it processed errors with checkResponse?

**Comment by ajrice6713** [comment]
@realmagic-eanes I have no problem making the breaking change since we can release a new major version, I would actually rather prefer that over an optional flag, I think that would make it even more unclear. 

Mostly just trying to see if breaking it would cause more headache on your side - and if you prefer the flag we can do that too (i think that would be more work than breaking it because we would need to add that as an option to every method on every model we want that flag)

**Comment by realmagic-eanes** [comment]
We have a workaround in place for the issue.  The new major version with the breaking change is fine for us!

**Comment by ajrice6713** [comment]
This change will go out tomorrow in our v8.0.0 release - If you guys have any questions, please let me know - I will close out this issue for the time being.
